# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Llama
version:      0.01
version_from: 
installdirs:  site
requires:
    Moose:                         2.0007

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
